### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8081/api/v1/weather/Andijon
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsInVzZXJuYW1lIjoia29taWxvdmxheml6YmVrNDgrMUBnbWFpbC5jb20iLCJzdWIiOiJrb21pbG92bGF6aXpiZWs0OCsxQGdtYWlsLmNvbSIsImlhdCI6MTczODM0NDg5MSwiZXhwIjoxNzM4NDMxMjkxfQ.q0pEpi3HG6jf-VUzteWdEPQKQubzjbNerFOI1m04FxbMif433_IwTKWlCip30rQV9p7C66WKyOvZXrB1E-1H3Q


####

#GET http://localhost:8081/api/v1/weather/cities?cities=London,Paris,Uzbekistan
#Content-Type: application/x-www-form-urlencoded
#Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMSIsInVzZXJuYW1lIjoia29taWxvdmxheml6YmVrNDgrMUBnbWFpbC5jb20iLCJzdWIiOiJrb21pbG92bGF6aXpiZWs0OCsxQGdtYWlsLmNvbSIsImlhdCI6MTczODM0NDg5MSwiZXhwIjoxNzM4NDMxMjkxfQ.q0pEpi3HG6jf-VUzteWdEPQKQubzjbNerFOI1m04FxbMif433_IwTKWlCip30rQV9p7C66WKyOvZXrB1E-1H3Q


