### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###
GET http://localhost:8081/api/v2/weather/Andijon
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMiIsInVzZXJuYW1lIjoia29taWxvdmxheml6YmVrNDgxQGdtYWlsLmNvbSIsInN1YiI6ImtvbWlsb3ZsYXppemJlazQ4MUBnbWFpbC5jb20iLCJpYXQiOjE3MzgyNDk2MzIsImV4cCI6MTczODMzNjAzMn0.Ou0g1VBapVtTjVpqLQu-Xb-b9vvYUvTyBYbWRpQPFIuuUBDfSHrDXUyzjOld_gh-ruHKiPyQBMVocrqV2550Ug


####

GET http://localhost:8081/api/v2/weather/cities?cities=London,Paris,Uzbekistan
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6IlJPTEVfVVNFUiIsImlkIjoiMiIsInVzZXJuYW1lIjoia29taWxvdmxheml6YmVrNDgxQGdtYWlsLmNvbSIsInN1YiI6ImtvbWlsb3ZsYXppemJlazQ4MUBnbWFpbC5jb20iLCJpYXQiOjE3MzgyNDk0NjgsImV4cCI6MTczODMzNTg2OH0.HNZkJsC5YtwC9ZSGJuswdVDVtahEKLfZa1Qv6pHxuy5FL6nQseo1CFHclEKWVNBSQhuhj7APQo8blJQJMZJaBA


